model:
  path: models/
  weights: imagenet     # new, last, coco, imagenet or custom path
  epochs: 20       # number of epochs to train for
  settings:
    name: latim_dataset
    image_shape: [512,512]
    image_channel_count: 1
    mean_pixel: [128] #, 128, 128]
    backbone: resnet50
    max_gt_instances: 10
    gpu_count: 1
    images_per_gpu: 1
    learning_rate: 0.01

dataset:
  path: latim_dataset/images/
  train_indices: train_indices.npy
  val_indices: test_indices.npy
  images: depth_ims
  masks: semantic_masks
  num_classes: 3
  labels: labels

# name of the config file to save (within the dataset folder)
# note that this will be overwritten between multiple runs so
# you should name this uniquely for each run.
save_conf_name: pretrained_res50.yaml
